import { createGlobalTheme } from "@vanilla-extract/css"

export const theme = createGlobalTheme(`:root`, {
  colors: {
    border: "#d2d2d2",
    current: "currentColor",
    default: "#1d1d1f",
    focus: "hsl(210deg 100% 49% / 60%)",
    highlight: "#f92672",
    hover: "#0077ed",
    link: "#06c",
    section: "#f5f5f5",
    text: "#1d1d1f",
    transparent: "transparent",
    unit: "#fff",
  },
  font: {
    family: {
      code: `Menlo, Consolas, Monaco, Liberation Mono, Lucida Console, monospace`,
      body: `-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"`,
      heading: `-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"`,
    },
    weight: {
      default: "400",
      thin: "100",
      extralight: "200",
      light: "300",
      normal: "400",
      medium: "500",
      semibold: "600",
      bold: "700",
      extrabold: "800",
      black: "900",
    },
    size: {
      default: "18px",
      xsmall: "8px",
      small: "12px",
      medium: "16px",
      large: "20px",
      xlarge: "24px",
      xxlarge: "32px",
      huge: "50px",
    },
  },
  spacing: {
    default: "16px",
    xsmall: "4px",
    small: "8px",
    medium: "12px",
    large: "24px",
    xlarge: "32px",
    xxlarge: "48px",
  },
})
